config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[index create]
  resources :weapons, only: %i[index create show destroy]
  resources :enemies, only: %i[index create show update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  enum kind: [ :goblin, :orc, :demon, :dragon ]
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }
  validates_presence_of :name, :power_base, :power_step, :level, :kind

  def current_power
    power_base + ((level - 1) * power_step)
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: [ :knight, :wizard ]

  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  def title
    "#{self.kind} #{self.nickname} ##{self.level}"
  end
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  attribute :level, :integer, default: 1
  attribute :power_step, :integer, default: 100
  attribute :power_base, :integer, default: 3000

  validates :power_step, numericality: { equal_to: 100 }
  validates :power_base, numericality: { greater_than_or_equal_to: 3000 }
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  def title
    "#{name} ##{level}"
  end

  def current_power
    power_base + ((level-1) * power_step)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :set_enemy, except: %i[index create]

  def index
    @enemies = Enemy.all
    if @enemies.blank?
      render json: { message: 'No enemies' }, status: :not_found
    else
      render json: @enemies, status: :ok
    end
  end

  def show
    render json: @enemy, status: :ok
  end

  def create
    @enemy = Enemy.new(enemy_params)
    if @enemy.save
      render json: @enemy, status: :created
    else
      render json: { errors: @enemy.errors }, status: :bad_request
    end
  end

  def update
    if @enemy.update(enemy_params)
      render json: @enemy, status: :ok
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @enemy.destroy
    head 204
  end

  private

  def enemy_params
    params.require(:enemy).permit(:name, :power_base, :power_step, :level, :kind)
  end

  def set_enemy
    @enemy = Enemy.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }, status: :not_found
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController

  def index
    @weapons = Weapon.all
  end

  def create
    @weapon = Weapon.create(weapon_params)
    redirect_to weapons_path
  end

  def destroy
    @weapon ||= find_weapon
    @weapon.destroy
  end

  def show
    @weapon ||= find_weapon
    @weapon
  end

  private

  def weapon_params
    params.require(:weapon).permit(:name, :description, :level, :power_base, :power_step)
  end

  def find_weapon
    @weapon = Weapon.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enemies/destroy.html.erb
<h1>Enemies#destroy</h1>
<p>Find me in app/views/enemies/destroy.html.erb</p>

app/views/enemies/update.html.erb
<h1>Enemies#update</h1>
<p>Find me in app/views/enemies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLikeAHero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <p><%= user.title %></p>
<% end %>

app/views/weapons/index.html.erb
<% @weapons.each do |weapon| %>
    <p><%= weapon.name %></p>
    <p><%= weapon.current_power %></p>
    <p><%= weapon.title %></p>
    <%= link_to "Details", weapon_path(weapon) %>
<% end %>

app/views/weapons/show.html.erb
<% unless @weapon.nil? %>
    <p><%= @weapon.name %></p>
    <p><%= @weapon.description %></p>
    <p><%= @weapon.power_base %></p>
    <p><%= @weapon.power_step %></p>
    <p><%= @weapon.level %></p>
    <p><%= @weapon.title %></p>
    <p><%= @weapon.current_power %></p>
<% end %>